# Generated by Django 5.0.3 on 2024-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='maximum_reservation',
            field=models.IntegerField(default=3),
        ),
    ]
